apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: default
      server: https://192.168.252.199:6443
    k8sVersion: v1.9.3
    path: default
kind: ksonnet.io/app
name: myapp
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
